language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --all-features --workspace
  - cargo test --verbose --all-features --workspace -- --ignored

env:
  global:
    # Default local config
    - BOLT_TEST_ADDR=127.0.0.1:7687
    - BOLT_TEST_USERNAME=neo4j
    - BOLT_TEST_PASSWORD=neo4j
  jobs:
    - NEO4J_VERSION=3.1
    - NEO4J_VERSION=3.2
    - NEO4J_VERSION=3.3
    - NEO4J_VERSION=3.4
    - NEO4J_VERSION=3.5
    - NEO4J_VERSION=4.0
    - NEO4J_VERSION=4.1

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - |
    if [[ $NEO4J_VERSION ]]; then
      docker pull neo4j:$NEO4J_VERSION
      docker run -d -p 7474:7474 -p 7687:7687 neo4j:$NEO4J_VERSION bash -c "neo4j-admin set-initial-password neo4j; neo4j console"
      docker ps -a
    fi

services:
  - docker
