[package]
name = "bolt-proto-derive"
version = "0.3.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
description = "Procedural macros for bolt-proto.\n"
repository = "https://github.com/lucis-fluxum/bolt-rs"
keywords    = ["bolt", "derive"]
license = "MIT"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.16"
quote = "1.0.3"
